sudo: false
language: node_js
node_js:
  - "9"
  - "8"
  - "6"

env:
  global:
    - SAUCE_USERNAME='shtylman-superagent'
    - SAUCE_ACCESS_KEY='39a45464-cb1d-4b8d-aa1f-83c7c04fa673'

matrix:
  include:
    - node_js: "9"
      env: BROWSER=1
    - node_js: "9"
      env: EXPOSE_HTTP2=1
    - node_js: "8"
      env: EXPOSE_HTTP2=1

before_install:
  - "test -z $(echo $EXPOSE_HTTP2) || npm install --only=dev https://github.com/sogaani/express.git#initial-support-http2"
